name: Build and Push image to GHCR

on:
  push:
    branches: [main]
    paths:
      - 'Dockerfile'
      - 'server.js'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        id: image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/node-app
          echo "name=$IMAGE_NAME" >> $GITHUB_OUTPUT

      - name: check some things
        run: |
          ls -l ${{ github.workspace }}
          env
          echo "${{ steps.image.outputs.name }}"

      - name: Build Docker image
        run: |
          docker build -t ${{ steps.image.outputs.name }}:${{ github.sha }} .

      - name: Push Docker image
        run: |
          docker push ${{ steps.image.outputs.name }}:${{ github.sha }}
          docker tag ${{ steps.image.outputs.name }}:${{ github.sha }} ${{ steps.image.outputs.name }}:latest
          docker push ${{ steps.image.outputs.name }}:latest
